#!/bin/zsh
set -euo pipefail

MAC_ROOT="${0:A:h:h}"
OUTPUT_JSON=false
MODE_WAS_EXPLICIT=false
DELIVERY_INPUT=""

usage() {
  /bin/cat <<'EOF'
Usage:
  ./verify-macos-app-store-delivery.sh [--check] DELIVERY.json
  ./verify-macos-app-store-delivery.sh --json DELIVERY.json

Independently re-verifies a read-only Mac App Store delivery record, every
local artifact and hash it binds, and the exact package candidate. --json emits
a stable machine-readable result for release-readiness.sh. Neither mode
contacts Apple or claims that App Store Connect processing is Complete.
EOF
}

fail() {
  print -u2 -r -- "macOS App Store delivery verification failed: $*"
  exit 2
}

while (( $# > 0 )); do
  case "$1" in
    --check)
      [[ "$MODE_WAS_EXPLICIT" == false ]] || fail "choose only one of --check or --json"
      OUTPUT_JSON=false
      MODE_WAS_EXPLICIT=true
      ;;
    --json)
      [[ "$MODE_WAS_EXPLICIT" == false ]] || fail "choose only one of --check or --json"
      OUTPUT_JSON=true
      MODE_WAS_EXPLICIT=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      fail "unknown option: $1"
      ;;
    *)
      [[ -z "$DELIVERY_INPUT" ]] || fail "only one delivery record may be supplied"
      DELIVERY_INPUT="$1"
      ;;
  esac
  shift
done

[[ -n "$DELIVERY_INPUT" ]] || fail "a delivery record is required"
[[ -f "$DELIVERY_INPUT" && ! -L "$DELIVERY_INPUT" ]] \
  || fail "delivery record must be an existing, non-symlink file"
DELIVERY_INPUT_ABSOLUTE="${DELIVERY_INPUT:a}"
DELIVERY_RECORD_PATH="${DELIVERY_INPUT:A}"
[[ "$DELIVERY_INPUT_ABSOLUTE" == "$DELIVERY_RECORD_PATH" ]] \
  || fail "delivery record path must not traverse symlink parents"
[[ "${DELIVERY_RECORD_PATH:t}" == mac-app-store-delivery-*.json ]] \
  || fail "delivery record filename is not generated by the submission script"
RELEASE_DIRECTORY="${DELIVERY_RECORD_PATH:h}"
[[ -d "$RELEASE_DIRECTORY" && ! -L "$RELEASE_DIRECTORY" ]] \
  || fail "delivery record parent must be a non-symlink release directory"
[[ "$RELEASE_DIRECTORY" == "${RELEASE_DIRECTORY:A}" ]] \
  || fail "release directory must already be a canonical candidate root"

for tool in /usr/bin/jq /usr/bin/shasum /usr/bin/stat; do
  [[ -x "$tool" ]] || fail "required tool is unavailable: $tool"
done
[[ -x "$MAC_ROOT/scripts/submit-macos-app-store.sh" ]] \
  || fail "submit-macos-app-store.sh is missing or not executable"

require_read_only() {
  local path="$1"
  local label="$2"
  local mode
  mode="$(/usr/bin/stat -f '%Lp' "$path")"
  [[ "$mode" == <-> ]] || fail "$label permissions are unreadable"
  (( (8#$mode & 8#222) == 0 )) || fail "$label must be read-only"
}
require_read_only "$DELIVERY_RECORD_PATH" "delivery record"

/usr/bin/jq -e '
  type == "object" and
  .schemaVersion == 1 and .platform == "macOS" and
  .destination == "App Store Connect / Mac App Store" and
  (.submittedAt | type == "string" and length > 0) and
  (.appBundleID | type == "string" and length > 0) and
  (.version | type == "string" and length > 0) and
  (.build | type == "string" and length > 0) and
  (.archiveZipPath | type == "string" and length > 0) and
  (.archiveZipSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.packagePath | type == "string" and length > 0) and
  (.packageSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.releaseMetadataPath | type == "string" and length > 0) and
  (.releaseMetadataSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.validationResultPath | type == "string" and length > 0) and
  (.validationResultSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.uploadResultPath | type == "string" and length > 0) and
  (.uploadResultSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  .uploadAccepted == true and .processingState == null and
  .appStoreConnectBuildID == null and .processingVerified == false and
  .processingVerifiedAt == null and .warningsReviewed == false and
  .warningsReviewedAt == null and .submittedForAppReview == false
' "$DELIVERY_RECORD_PATH" >/dev/null \
  || fail "delivery record has an invalid pre-processing schema"

APP_BUNDLE_ID="$(/usr/bin/jq -r '.appBundleID' "$DELIVERY_RECORD_PATH")"
VERSION="$(/usr/bin/jq -r '.version' "$DELIVERY_RECORD_PATH")"
BUILD_NUMBER="$(/usr/bin/jq -r '.build' "$DELIVERY_RECORD_PATH")"
SUBMITTED_AT="$(/usr/bin/jq -r '.submittedAt' "$DELIVERY_RECORD_PATH")"
ARCHIVE_ZIP_PATH="$(/usr/bin/jq -r '.archiveZipPath' "$DELIVERY_RECORD_PATH")"
ARCHIVE_ZIP_SHA256="$(/usr/bin/jq -r '.archiveZipSHA256' "$DELIVERY_RECORD_PATH")"
PACKAGE_PATH="$(/usr/bin/jq -r '.packagePath' "$DELIVERY_RECORD_PATH")"
PACKAGE_SHA256="$(/usr/bin/jq -r '.packageSHA256' "$DELIVERY_RECORD_PATH")"
RELEASE_METADATA_PATH="$(/usr/bin/jq -r '.releaseMetadataPath' "$DELIVERY_RECORD_PATH")"
RELEASE_METADATA_SHA256="$(/usr/bin/jq -r '.releaseMetadataSHA256' "$DELIVERY_RECORD_PATH")"
VALIDATION_RESULT_PATH="$(/usr/bin/jq -r '.validationResultPath' "$DELIVERY_RECORD_PATH")"
VALIDATION_RESULT_SHA256="$(/usr/bin/jq -r '.validationResultSHA256' "$DELIVERY_RECORD_PATH")"
UPLOAD_RESULT_PATH="$(/usr/bin/jq -r '.uploadResultPath' "$DELIVERY_RECORD_PATH")"
UPLOAD_RESULT_SHA256="$(/usr/bin/jq -r '.uploadResultSHA256' "$DELIVERY_RECORD_PATH")"

DELIVERY_BASENAME="${DELIVERY_RECORD_PATH:t}"
DELIVERY_STAMP="${DELIVERY_BASENAME#mac-app-store-delivery-}"
DELIVERY_STAMP="${DELIVERY_STAMP%.json}"
print -r -- "$DELIVERY_STAMP" | /usr/bin/grep -Eq \
  '^[0-9]{8}T[0-9]{6}Z$' \
  || fail "delivery record filename has an invalid UTC timestamp"

require_release_file() {
  local raw_path="$1"
  local label="$2"
  [[ "$raw_path" == /* && -f "$raw_path" && ! -L "$raw_path" ]] \
    || fail "$label must be an existing, absolute, non-symlink file"
  local canonical_path="${raw_path:A}"
  [[ "$raw_path" == "$canonical_path" ]] \
    || fail "$label path must already be canonical and must not traverse symlink parents"
  [[ "$canonical_path" == "$RELEASE_DIRECTORY"/* ]] \
    || fail "$label escapes the release directory"
  print -r -- "$canonical_path"
}

ARCHIVE_ZIP_PATH="$(require_release_file "$ARCHIVE_ZIP_PATH" "Archive ZIP")"
PACKAGE_PATH="$(require_release_file "$PACKAGE_PATH" "App Store package")"
RELEASE_METADATA_PATH="$(require_release_file "$RELEASE_METADATA_PATH" "release metadata")"
VALIDATION_RESULT_PATH="$(require_release_file "$VALIDATION_RESULT_PATH" "validation result")"
UPLOAD_RESULT_PATH="$(require_release_file "$UPLOAD_RESULT_PATH" "upload result")"
[[ "$RELEASE_METADATA_PATH" == "$RELEASE_DIRECTORY/release-metadata.json" ]] \
  || fail "delivery record references the wrong release metadata"
[[ "${VALIDATION_RESULT_PATH:t}" == \
    "mac-app-store-validation-$DELIVERY_STAMP.json" ]] \
  || fail "validation result does not share the delivery timestamp"
[[ "${UPLOAD_RESULT_PATH:t}" == "mac-app-store-upload-$DELIVERY_STAMP.json" ]] \
  || fail "upload result does not share the delivery timestamp"
require_read_only "$VALIDATION_RESULT_PATH" "validation result"
require_read_only "$UPLOAD_RESULT_PATH" "upload result"

file_sha256() {
  LC_ALL=C LANG=C /usr/bin/shasum -a 256 "$1" | /usr/bin/awk '{print $1}'
}

verify_altool_success_json() {
  local result_path="$1"
  local operation="$2"
  /usr/bin/jq -s -e '
    length == 1 and
    (.[0] |
      type == "object" and
      (.["success-message"] | type == "string" and length > 0) and
      ((has("product-errors") | not) or
        .["product-errors"] == null or .["product-errors"] == []) and
      ((has("errors") | not) or .errors == null or .errors == [])
    )
  ' "$result_path" >/dev/null \
    || fail "App Store Connect $operation result does not contain an unambiguous altool success response"
}

[[ "$(file_sha256 "$ARCHIVE_ZIP_PATH")" == "$ARCHIVE_ZIP_SHA256" ]] \
  || fail "Archive ZIP differs from delivery record"
[[ "$(file_sha256 "$PACKAGE_PATH")" == "$PACKAGE_SHA256" ]] \
  || fail "App Store package differs from delivery record"
[[ "$(file_sha256 "$RELEASE_METADATA_PATH")" == "$RELEASE_METADATA_SHA256" ]] \
  || fail "release metadata differs from delivery record"
[[ "$(file_sha256 "$VALIDATION_RESULT_PATH")" == "$VALIDATION_RESULT_SHA256" ]] \
  || fail "validation result differs from delivery record"
[[ "$(file_sha256 "$UPLOAD_RESULT_PATH")" == "$UPLOAD_RESULT_SHA256" ]] \
  || fail "upload result differs from delivery record"
verify_altool_success_json "$VALIDATION_RESULT_PATH" "validation"
verify_altool_success_json "$UPLOAD_RESULT_PATH" "upload"

/usr/bin/jq -e \
  --arg bundle "$APP_BUNDLE_ID" --arg version "$VERSION" --arg build "$BUILD_NUMBER" \
  --arg archiveZip "$ARCHIVE_ZIP_PATH" --arg archiveSHA "$ARCHIVE_ZIP_SHA256" \
  --arg package "$PACKAGE_PATH" --arg packageSHA "$PACKAGE_SHA256" '
    .schemaVersion == 1 and .platform == "macOS" and
    .distribution == "mac-app-store" and .appBundleID == $bundle and
    .version == $version and .build == $build and
    .archiveZip == $archiveZip and .archiveZipSHA256 == $archiveSHA and
    .exportedPackage == $package and .packageSHA256 == $packageSHA and
    .applicationCategory == "public.app-category.developer-tools" and
    (.createdAt | type == "string" and length > 0) and
    .uploaded == false
  ' "$RELEASE_METADATA_PATH" >/dev/null \
  || fail "release metadata and delivery record do not bind the same candidate"

valid_utc_timestamp() {
  local value="$1"
  print -r -- "$value" | /usr/bin/grep -Eq \
    '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$' \
    || return 1
  /bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$value" '+%s' >/dev/null 2>&1
}
valid_utc_timestamp "$SUBMITTED_AT" || fail "delivery submittedAt is invalid"
METADATA_CREATED_AT="$(/usr/bin/jq -r '.createdAt' "$RELEASE_METADATA_PATH")"
valid_utc_timestamp "$METADATA_CREATED_AT" \
  || fail "release metadata createdAt is invalid"
DELIVERY_STAMP_ISO="$(print -r -- "$DELIVERY_STAMP" | /usr/bin/sed -E \
  's/^([0-9]{4})([0-9]{2})([0-9]{2})T([0-9]{2})([0-9]{2})([0-9]{2})Z$/\1-\2-\3T\4:\5:\6Z/')"
valid_utc_timestamp "$DELIVERY_STAMP_ISO" \
  || fail "delivery filename timestamp is not a real UTC time"
METADATA_CREATED_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' \
  "$METADATA_CREATED_AT" '+%s')"
DELIVERY_STAMP_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' \
  "$DELIVERY_STAMP_ISO" '+%s')"
SUBMITTED_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$SUBMITTED_AT" '+%s')"
NOW_EPOCH="$(/bin/date -u '+%s')"
(( METADATA_CREATED_EPOCH <= DELIVERY_STAMP_EPOCH && \
  DELIVERY_STAMP_EPOCH <= SUBMITTED_EPOCH && SUBMITTED_EPOCH <= NOW_EPOCH + 300 )) \
  || fail "release and delivery timestamps are out of order"

"$MAC_ROOT/scripts/submit-macos-app-store.sh" --check "$RELEASE_DIRECTORY" >/dev/null \
  || fail "the exact package no longer passes local submission preflight"

DELIVERY_RECORD_SHA256="$(file_sha256 "$DELIVERY_RECORD_PATH")"
if [[ "$OUTPUT_JSON" == true ]]; then
  /usr/bin/jq -n \
    --arg deliveryRecordPath "$DELIVERY_RECORD_PATH" \
    --arg deliveryRecordSHA256 "$DELIVERY_RECORD_SHA256" \
    --arg releaseMetadataPath "$RELEASE_METADATA_PATH" \
    --arg releaseMetadataSHA256 "$RELEASE_METADATA_SHA256" \
    --arg archiveZipPath "$ARCHIVE_ZIP_PATH" \
    --arg archiveZipSHA256 "$ARCHIVE_ZIP_SHA256" \
    --arg packagePath "$PACKAGE_PATH" --arg packageSHA256 "$PACKAGE_SHA256" \
    --arg validationResultPath "$VALIDATION_RESULT_PATH" \
    --arg validationResultSHA256 "$VALIDATION_RESULT_SHA256" \
    --arg uploadResultPath "$UPLOAD_RESULT_PATH" \
    --arg uploadResultSHA256 "$UPLOAD_RESULT_SHA256" \
    --arg appBundleID "$APP_BUNDLE_ID" --arg version "$VERSION" \
    --arg build "$BUILD_NUMBER" --arg submittedAt "$SUBMITTED_AT" '{
      schemaVersion: 1,
      platform: "macOS",
      evidenceVerified: true,
      evidencePath: $deliveryRecordPath,
      evidenceSHA256: $deliveryRecordSHA256,
      deliveryRecordPath: $deliveryRecordPath,
      deliveryRecordSHA256: $deliveryRecordSHA256,
      releaseMetadataPath: $releaseMetadataPath,
      releaseMetadataSHA256: $releaseMetadataSHA256,
      archiveZipPath: $archiveZipPath,
      archiveZipSHA256: $archiveZipSHA256,
      packagePath: $packagePath,
      packageSHA256: $packageSHA256,
      validationResultPath: $validationResultPath,
      validationResultSHA256: $validationResultSHA256,
      uploadResultPath: $uploadResultPath,
      uploadResultSHA256: $uploadResultSHA256,
      appBundleID: $appBundleID,
      version: $version,
      build: $build,
      submittedAt: $submittedAt,
      uploadAccepted: true,
      processingState: null,
      processingVerified: false,
      submittedForAppReview: false
    }'
else
  print -r -- "Mac App Store delivery evidence verified."
  print -r -- "Bundle: $APP_BUNDLE_ID"
  print -r -- "Version/build: $VERSION ($BUILD_NUMBER)"
  print -r -- "PKG SHA-256: $PACKAGE_SHA256"
  print -r -- "Upload accepted; processing is not yet verified; App Review not submitted."
fi
