#!/bin/zsh
set -euo pipefail

MAC_ROOT="${0:A:h:h}"
OUTPUT_JSON=false
MODE_WAS_EXPLICIT=false
EVIDENCE_INPUT=""

usage() {
  /bin/cat <<'EOF'
Usage:
  ./verify-macos-app-store-evidence.sh [--check] PROCESSING_EVIDENCE.json
  ./verify-macos-app-store-evidence.sh --json PROCESSING_EVIDENCE.json

Re-verifies a read-only, no-overwrite Mac App Store processing-evidence record and every
local artifact it binds. --check prints a human summary; --json emits a stable
machine-readable result suitable for release-readiness.sh. No mode contacts or
changes App Store Connect.
EOF
}

fail() {
  print -u2 -r -- "macOS App Store evidence verification failed: $*"
  exit 2
}

while (( $# > 0 )); do
  case "$1" in
    --check)
      [[ "$MODE_WAS_EXPLICIT" == false ]] || fail "choose only one of --check or --json"
      OUTPUT_JSON=false
      MODE_WAS_EXPLICIT=true
      ;;
    --json)
      [[ "$MODE_WAS_EXPLICIT" == false ]] || fail "choose only one of --check or --json"
      OUTPUT_JSON=true
      MODE_WAS_EXPLICIT=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      fail "unknown option: $1"
      ;;
    *)
      [[ -z "$EVIDENCE_INPUT" ]] || fail "only one processing-evidence file may be supplied"
      EVIDENCE_INPUT="$1"
      ;;
  esac
  shift
done

[[ -n "$EVIDENCE_INPUT" ]] || fail "a processing-evidence file is required"
[[ -f "$EVIDENCE_INPUT" && ! -L "$EVIDENCE_INPUT" ]] \
  || fail "processing evidence must be an existing, non-symlink file"
EVIDENCE_INPUT_ABSOLUTE="${EVIDENCE_INPUT:a}"
EVIDENCE_PATH="${EVIDENCE_INPUT:A}"
[[ "$EVIDENCE_INPUT_ABSOLUTE" == "$EVIDENCE_PATH" ]] \
  || fail "processing evidence path must not traverse symlink parents"
[[ "${EVIDENCE_PATH:t}" == mac-app-store-processing-verification-*.json ]] \
  || fail "processing-evidence filename is not generated by the confirmation script"
RELEASE_DIRECTORY="${EVIDENCE_PATH:h}"
[[ -d "$RELEASE_DIRECTORY" && ! -L "$RELEASE_DIRECTORY" ]] \
  || fail "processing-evidence parent must be a non-symlink release directory"
[[ "$RELEASE_DIRECTORY" == "${RELEASE_DIRECTORY:A}" ]] \
  || fail "release directory must already be a canonical candidate root"

for tool in /usr/bin/jq /usr/bin/shasum /usr/bin/stat; do
  [[ -x "$tool" ]] || fail "required tool is unavailable: $tool"
done
[[ -x "$MAC_ROOT/scripts/submit-macos-app-store.sh" ]] \
  || fail "submit-macos-app-store.sh is missing or not executable"
[[ -x "$MAC_ROOT/scripts/verify-macos-app-store-delivery.sh" ]] \
  || fail "verify-macos-app-store-delivery.sh is missing or not executable"

require_read_only() {
  local path="$1"
  local label="$2"
  local mode
  mode="$(/usr/bin/stat -f '%Lp' "$path")"
  [[ "$mode" == <-> ]] || fail "$label permissions are unreadable"
  (( (8#$mode & 8#222) == 0 )) || fail "$label must be read-only"
}
require_read_only "$EVIDENCE_PATH" "processing evidence"

/usr/bin/jq -e '
  type == "object" and
  .schemaVersion == 1 and .platform == "macOS" and
  .destination == "App Store Connect / Mac App Store" and
  (.appBundleID | type == "string" and length > 0) and
  (.version | type == "string" and length > 0) and
  (.build | type == "string" and length > 0) and
  (.archiveZipPath | type == "string" and length > 0) and
  (.archiveZipSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.packagePath | type == "string" and length > 0) and
  (.packageSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.releaseMetadataPath | type == "string" and length > 0) and
  (.releaseMetadataSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.deliveryRecordPath | type == "string" and length > 0) and
  (.deliveryRecordSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.validationResultPath | type == "string" and length > 0) and
  (.validationResultSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  (.uploadResultPath | type == "string" and length > 0) and
  (.uploadResultSHA256 | type == "string" and test("^[0-9a-f]{64}$")) and
  .uploadAccepted == true and
  (.appStoreConnectBuildID | type == "string" and length > 0 and length <= 256) and
  .processingState == "Complete" and .processingVerified == true and
  (.processingVerifiedAt | type == "string" and length > 0) and
  .warningsReviewed == true and
  .warningsReviewedAt == .processingVerifiedAt and
  .submittedForAppReview == false and
  (.createdAt | type == "string" and length > 0)
' "$EVIDENCE_PATH" >/dev/null || fail "processing evidence has an invalid schema"

APP_BUNDLE_ID="$(/usr/bin/jq -r '.appBundleID' "$EVIDENCE_PATH")"
VERSION="$(/usr/bin/jq -r '.version' "$EVIDENCE_PATH")"
BUILD_NUMBER="$(/usr/bin/jq -r '.build' "$EVIDENCE_PATH")"
ARCHIVE_ZIP_PATH="$(/usr/bin/jq -r '.archiveZipPath' "$EVIDENCE_PATH")"
ARCHIVE_ZIP_SHA256="$(/usr/bin/jq -r '.archiveZipSHA256' "$EVIDENCE_PATH")"
PACKAGE_PATH="$(/usr/bin/jq -r '.packagePath' "$EVIDENCE_PATH")"
PACKAGE_SHA256="$(/usr/bin/jq -r '.packageSHA256' "$EVIDENCE_PATH")"
RELEASE_METADATA_PATH="$(/usr/bin/jq -r '.releaseMetadataPath' "$EVIDENCE_PATH")"
RELEASE_METADATA_SHA256="$(/usr/bin/jq -r '.releaseMetadataSHA256' "$EVIDENCE_PATH")"
DELIVERY_RECORD_PATH="$(/usr/bin/jq -r '.deliveryRecordPath' "$EVIDENCE_PATH")"
DELIVERY_RECORD_SHA256="$(/usr/bin/jq -r '.deliveryRecordSHA256' "$EVIDENCE_PATH")"
VALIDATION_RESULT_PATH="$(/usr/bin/jq -r '.validationResultPath' "$EVIDENCE_PATH")"
VALIDATION_RESULT_SHA256="$(/usr/bin/jq -r '.validationResultSHA256' "$EVIDENCE_PATH")"
UPLOAD_RESULT_PATH="$(/usr/bin/jq -r '.uploadResultPath' "$EVIDENCE_PATH")"
UPLOAD_RESULT_SHA256="$(/usr/bin/jq -r '.uploadResultSHA256' "$EVIDENCE_PATH")"
APP_STORE_CONNECT_BUILD_ID="$(/usr/bin/jq -r '.appStoreConnectBuildID' "$EVIDENCE_PATH")"
PROCESSING_VERIFIED_AT="$(/usr/bin/jq -r '.processingVerifiedAt' "$EVIDENCE_PATH")"
CREATED_AT="$(/usr/bin/jq -r '.createdAt' "$EVIDENCE_PATH")"

print -r -- "$APP_STORE_CONNECT_BUILD_ID" | LC_ALL=C /usr/bin/grep -Eq '^[[:graph:]]+$' \
  || fail "App Store Connect Build ID contains whitespace or control characters"
case "${APP_STORE_CONNECT_BUILD_ID:l}" in
  *placeholder*|*example*|*your*|*build-id*|*build_id*|todo|tbd|unknown|null|none|\<*|*\>)
    fail "App Store Connect Build ID is still a placeholder"
    ;;
esac

require_release_file() {
  local raw_path="$1"
  local label="$2"
  [[ "$raw_path" == /* && -f "$raw_path" && ! -L "$raw_path" ]] \
    || fail "$label must be an existing, absolute, non-symlink file"
  local canonical_path="${raw_path:A}"
  [[ "$raw_path" == "$canonical_path" ]] \
    || fail "$label path must already be canonical and must not traverse symlink parents"
  [[ "$canonical_path" == "$RELEASE_DIRECTORY"/* ]] \
    || fail "$label escapes the release directory"
  print -r -- "$canonical_path"
}

ARCHIVE_ZIP_PATH="$(require_release_file "$ARCHIVE_ZIP_PATH" "Archive ZIP")"
PACKAGE_PATH="$(require_release_file "$PACKAGE_PATH" "App Store package")"
RELEASE_METADATA_PATH="$(require_release_file "$RELEASE_METADATA_PATH" "release metadata")"
DELIVERY_RECORD_PATH="$(require_release_file "$DELIVERY_RECORD_PATH" "delivery record")"
VALIDATION_RESULT_PATH="$(require_release_file "$VALIDATION_RESULT_PATH" "validation result")"
UPLOAD_RESULT_PATH="$(require_release_file "$UPLOAD_RESULT_PATH" "upload result")"
[[ "$RELEASE_METADATA_PATH" == "$RELEASE_DIRECTORY/release-metadata.json" ]] \
  || fail "processing evidence references the wrong release metadata"
[[ "${DELIVERY_RECORD_PATH:t}" == mac-app-store-delivery-*.json ]] \
  || fail "processing evidence references a non-generated delivery record"
require_read_only "$DELIVERY_RECORD_PATH" "delivery record"
require_read_only "$VALIDATION_RESULT_PATH" "validation result"
require_read_only "$UPLOAD_RESULT_PATH" "upload result"

file_sha256() {
  LC_ALL=C LANG=C /usr/bin/shasum -a 256 "$1" | /usr/bin/awk '{print $1}'
}
[[ "$(file_sha256 "$ARCHIVE_ZIP_PATH")" == "$ARCHIVE_ZIP_SHA256" ]] \
  || fail "Archive ZIP differs from processing evidence"
[[ "$(file_sha256 "$PACKAGE_PATH")" == "$PACKAGE_SHA256" ]] \
  || fail "App Store package differs from processing evidence"
[[ "$(file_sha256 "$RELEASE_METADATA_PATH")" == "$RELEASE_METADATA_SHA256" ]] \
  || fail "release metadata differs from processing evidence"
[[ "$(file_sha256 "$DELIVERY_RECORD_PATH")" == "$DELIVERY_RECORD_SHA256" ]] \
  || fail "delivery record differs from processing evidence"
[[ "$(file_sha256 "$VALIDATION_RESULT_PATH")" == "$VALIDATION_RESULT_SHA256" ]] \
  || fail "validation result differs from processing evidence"
[[ "$(file_sha256 "$UPLOAD_RESULT_PATH")" == "$UPLOAD_RESULT_SHA256" ]] \
  || fail "upload result differs from processing evidence"
/usr/bin/jq -e . "$VALIDATION_RESULT_PATH" >/dev/null \
  || fail "validation result is no longer valid JSON"
/usr/bin/jq -e . "$UPLOAD_RESULT_PATH" >/dev/null \
  || fail "upload result is no longer valid JSON"

/usr/bin/jq -e \
  --arg bundle "$APP_BUNDLE_ID" --arg version "$VERSION" --arg build "$BUILD_NUMBER" \
  --arg archiveZip "$ARCHIVE_ZIP_PATH" --arg archiveSHA "$ARCHIVE_ZIP_SHA256" \
  --arg package "$PACKAGE_PATH" --arg packageSHA "$PACKAGE_SHA256" \
  --arg metadata "$RELEASE_METADATA_PATH" --arg metadataSHA "$RELEASE_METADATA_SHA256" \
  --arg validation "$VALIDATION_RESULT_PATH" --arg validationSHA "$VALIDATION_RESULT_SHA256" \
  --arg upload "$UPLOAD_RESULT_PATH" --arg uploadSHA "$UPLOAD_RESULT_SHA256" '
    .schemaVersion == 1 and .platform == "macOS" and
    .destination == "App Store Connect / Mac App Store" and
    .appBundleID == $bundle and .version == $version and .build == $build and
    .archiveZipPath == $archiveZip and .archiveZipSHA256 == $archiveSHA and
    .packagePath == $package and .packageSHA256 == $packageSHA and
    .releaseMetadataPath == $metadata and .releaseMetadataSHA256 == $metadataSHA and
    .validationResultPath == $validation and .validationResultSHA256 == $validationSHA and
    .uploadResultPath == $upload and .uploadResultSHA256 == $uploadSHA and
    .uploadAccepted == true and .processingState == null and
    .appStoreConnectBuildID == null and .processingVerified == false and
    .warningsReviewed == false and .submittedForAppReview == false
  ' "$DELIVERY_RECORD_PATH" >/dev/null \
  || fail "delivery record and processing evidence do not bind the same upload"

/usr/bin/jq -e \
  --arg bundle "$APP_BUNDLE_ID" --arg version "$VERSION" --arg build "$BUILD_NUMBER" \
  --arg archiveZip "$ARCHIVE_ZIP_PATH" --arg archiveSHA "$ARCHIVE_ZIP_SHA256" \
  --arg package "$PACKAGE_PATH" --arg packageSHA "$PACKAGE_SHA256" '
    .schemaVersion == 1 and .platform == "macOS" and
    .distribution == "mac-app-store" and .appBundleID == $bundle and
    .version == $version and .build == $build and
    .archiveZip == $archiveZip and .archiveZipSHA256 == $archiveSHA and
    .exportedPackage == $package and .packageSHA256 == $packageSHA and
    .applicationCategory == "public.app-category.developer-tools" and
    .uploaded == false
  ' "$RELEASE_METADATA_PATH" >/dev/null \
  || fail "release metadata and processing evidence do not bind the same candidate"

valid_utc_timestamp() {
  local value="$1"
  print -r -- "$value" | /usr/bin/grep -Eq \
    '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$' \
    || return 1
  /bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$value" '+%s' >/dev/null 2>&1
}
SUBMITTED_AT="$(/usr/bin/jq -r '.submittedAt' "$DELIVERY_RECORD_PATH")"
valid_utc_timestamp "$SUBMITTED_AT" || fail "delivery submittedAt is invalid"
valid_utc_timestamp "$PROCESSING_VERIFIED_AT" || fail "processingVerifiedAt is invalid"
valid_utc_timestamp "$CREATED_AT" || fail "evidence createdAt is invalid"
SUBMITTED_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$SUBMITTED_AT" '+%s')"
PROCESSING_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$PROCESSING_VERIFIED_AT" '+%s')"
CREATED_EPOCH="$(/bin/date -j -u -f '%Y-%m-%dT%H:%M:%SZ' "$CREATED_AT" '+%s')"
NOW_EPOCH="$(/bin/date -u '+%s')"
(( SUBMITTED_EPOCH <= PROCESSING_EPOCH && PROCESSING_EPOCH <= CREATED_EPOCH && \
  CREATED_EPOCH <= NOW_EPOCH + 300 )) || fail "evidence timestamps are out of order"

DELIVERY_VERIFICATION_JSON="$(
  "$MAC_ROOT/scripts/verify-macos-app-store-delivery.sh" \
    --json "$DELIVERY_RECORD_PATH"
)" || fail "the bound delivery record no longer passes independent verification"
/usr/bin/jq -e \
  --arg delivery "$DELIVERY_RECORD_PATH" --arg deliverySHA "$DELIVERY_RECORD_SHA256" \
  --arg metadata "$RELEASE_METADATA_PATH" --arg metadataSHA "$RELEASE_METADATA_SHA256" \
  --arg archive "$ARCHIVE_ZIP_PATH" --arg archiveSHA "$ARCHIVE_ZIP_SHA256" \
  --arg package "$PACKAGE_PATH" --arg packageSHA "$PACKAGE_SHA256" \
  --arg validation "$VALIDATION_RESULT_PATH" --arg validationSHA "$VALIDATION_RESULT_SHA256" \
  --arg upload "$UPLOAD_RESULT_PATH" --arg uploadSHA "$UPLOAD_RESULT_SHA256" \
  --arg bundle "$APP_BUNDLE_ID" --arg version "$VERSION" --arg build "$BUILD_NUMBER" \
  --arg submittedAt "$SUBMITTED_AT" '
    .schemaVersion == 1 and .platform == "macOS" and
    .evidenceVerified == true and .uploadAccepted == true and
    .evidencePath == $delivery and .evidenceSHA256 == $deliverySHA and
    .deliveryRecordPath == $delivery and .deliveryRecordSHA256 == $deliverySHA and
    .releaseMetadataPath == $metadata and .releaseMetadataSHA256 == $metadataSHA and
    .archiveZipPath == $archive and .archiveZipSHA256 == $archiveSHA and
    .packagePath == $package and .packageSHA256 == $packageSHA and
    .validationResultPath == $validation and .validationResultSHA256 == $validationSHA and
    .uploadResultPath == $upload and .uploadResultSHA256 == $uploadSHA and
    .appBundleID == $bundle and .version == $version and .build == $build and
    .submittedAt == $submittedAt and .processingState == null and
    .processingVerified == false and .submittedForAppReview == false
  ' <<<"$DELIVERY_VERIFICATION_JSON" >/dev/null \
  || fail "independent delivery verification does not bind the same exact candidate"

EVIDENCE_SHA256="$(file_sha256 "$EVIDENCE_PATH")"
if [[ "$OUTPUT_JSON" == true ]]; then
  /usr/bin/jq -n \
    --arg evidencePath "$EVIDENCE_PATH" --arg evidenceSHA256 "$EVIDENCE_SHA256" \
    --arg deliveryRecordPath "$DELIVERY_RECORD_PATH" \
    --arg deliveryRecordSHA256 "$DELIVERY_RECORD_SHA256" \
    --arg releaseMetadataPath "$RELEASE_METADATA_PATH" \
    --arg releaseMetadataSHA256 "$RELEASE_METADATA_SHA256" \
    --arg archiveZipPath "$ARCHIVE_ZIP_PATH" \
    --arg archiveZipSHA256 "$ARCHIVE_ZIP_SHA256" \
    --arg appBundleID "$APP_BUNDLE_ID" --arg version "$VERSION" \
    --arg build "$BUILD_NUMBER" --arg packagePath "$PACKAGE_PATH" \
    --arg packageSHA256 "$PACKAGE_SHA256" \
    --arg validationResultPath "$VALIDATION_RESULT_PATH" \
    --arg validationResultSHA256 "$VALIDATION_RESULT_SHA256" \
    --arg uploadResultPath "$UPLOAD_RESULT_PATH" \
    --arg uploadResultSHA256 "$UPLOAD_RESULT_SHA256" \
    --arg submittedAt "$SUBMITTED_AT" \
    --arg appStoreConnectBuildID "$APP_STORE_CONNECT_BUILD_ID" \
    --arg processingVerifiedAt "$PROCESSING_VERIFIED_AT" \
    --arg warningsReviewedAt "$PROCESSING_VERIFIED_AT" \
    --arg createdAt "$CREATED_AT" '{
      schemaVersion: 1,
      platform: "macOS",
      evidenceVerified: true,
      deliveryEvidenceVerified: true,
      evidencePath: $evidencePath,
      evidenceSHA256: $evidenceSHA256,
      deliveryRecordPath: $deliveryRecordPath,
      deliveryRecordSHA256: $deliveryRecordSHA256,
      releaseMetadataPath: $releaseMetadataPath,
      releaseMetadataSHA256: $releaseMetadataSHA256,
      archiveZipPath: $archiveZipPath,
      archiveZipSHA256: $archiveZipSHA256,
      appBundleID: $appBundleID,
      version: $version,
      build: $build,
      packagePath: $packagePath,
      packageSHA256: $packageSHA256,
      validationResultPath: $validationResultPath,
      validationResultSHA256: $validationResultSHA256,
      uploadResultPath: $uploadResultPath,
      uploadResultSHA256: $uploadResultSHA256,
      submittedAt: $submittedAt,
      appStoreConnectBuildID: $appStoreConnectBuildID,
      uploadAccepted: true,
      processingState: "Complete",
      processingVerified: true,
      processingVerifiedAt: $processingVerifiedAt,
      warningsReviewed: true,
      warningsReviewedAt: $warningsReviewedAt,
      createdAt: $createdAt,
      submittedForAppReview: false
    }'
else
  print -r -- "Mac App Store processing evidence verified."
  print -r -- "Bundle: $APP_BUNDLE_ID"
  print -r -- "Version/build: $VERSION ($BUILD_NUMBER)"
  print -r -- "PKG SHA-256: $PACKAGE_SHA256"
  print -r -- "App Store Connect Build ID: $APP_STORE_CONNECT_BUILD_ID"
  print -r -- "Processing: Complete; warnings reviewed; App Review not submitted."
fi
